# Descriptions Generater

In [1]:
import pandas as pd
import json

### Artist Information

In [3]:
with open('artist_data/demographic_information.json', 'r') as file:
    demographic_data = json.load(file)

In [4]:
artist_data = pd.read_csv("artist_data/artist_data_new.csv")

print(artist_data.shape)

(3048, 20)

In [5]:
artist_data["url_name"] = artist_data["url_name"].str.replace("en/", "", regex=False)
artist_data.head()

,name,url_name,Birth Date,Death Date,Birth place,Death place,Nationality,Art Movement,Genre,Field,Influenced by,Influenced on,Wikipedia,Painting School,Official site,Friends and Co-workers,Family and Relatives,Pupils,Teachers,Art institution
0,Thomas Fearnley,thomas-fearnley,"December 27, 1802","January 16, 1842",Norway,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://en.wikipedia.org/wiki/Thomas_Fearnley,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Olusola David, Ayibiowu",olusola-david-ayibiowu,24-Jan-74,NaN,Nigeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://en.wikipedia.org/wiki/Nigerian_Nationa...,NaN,www.casfoundation.org.ng,NaN,NaN,NaN,NaN,NaN
2,Goran Despotovski,goran-despotovski,13-Aug-72,NaN,Serbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.gorandespotovski.com/,NaN,www.gorandespotovski.com,NaN,NaN,NaN,NaN,NaN
3,Chaim Goldberg,chaim-goldberg,20-Mar-17,NaN,Poland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://en.wikipedia.org/wiki/Chaim_Goldberg,NaN,chaimgoldberg.com,NaN,NaN,NaN,NaN,NaN
4,Ancient Greek Pottery,ancient-greek-pottery,c.900 BC,31 BC,NaN,NaN,Greeks|Italians|Turkish|Bulgarians|Macedonians...,Geometric Period (c.900 - c.700 BC)|Archaic Pe...,design,painting|design,Ancient Greek Painting and Sculpture|Ancient E...,Ancient Greek Painting and Sculpture,https://en.wikipedia.org/wiki/Pottery_of_ancie...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Artwork Information

In [6]:
artist_artwork = pd.read_csv("artist_data/artist_artwork.csv")
print(artist_artwork.shape)
artist_artwork.head()

(178581, 4)

,Artist_name,Artwork Name,Year,Link
0,ancient-greek-pottery,Attic Middle Geometric Amphora from Kerameikos,-800,https://www.wikiart.org/en/ancient-greek-potte...
1,ancient-greek-pottery,Attic Late Geometric Amphora. From Athens. By ...,-750,https://www.wikiart.org/en/ancient-greek-potte...
2,ancient-greek-pottery,Attic Late Geometric Pyxis with Four Horses on...,-735,https://www.wikiart.org/en/ancient-greek-potte...
3,ancient-greek-pottery,Hirschfeld Krater,-735,https://www.wikiart.org/en/ancient-greek-potte...
4,ancient-greek-pottery,Attic Geometric Trefoil Mouth Oinochoe. From A...,-725,https://www.wikiart.org/en/ancient-greek-potte...

In [7]:
artwork_data = pd.read_csv("artwork_data/artwork_data_image_done.csv")
print(artwork_data.shape)
artwork_data.head()

(195288, 15)

,url,Create Date,Create Location,Date,image_url,Style,Genre,Media,tags,Location,Series,Period,Theme,Share,image_n
0,https://www.wikiart.org/en/paul-emile-chabas/l...,1905,NaN,1905|c.1905; France,https://uploads2.wikiart.org/00396/images/paul...,Art Deco,nude painting (nu)|figurative,oil|canvas,female-nude,NaN,NaN,NaN,NaN,NaN,0.0
1,https://www.wikiart.org/en/thomas-dewing/the-d...,1886,NaN,1886,https://uploads4.wikiart.org/00114/images/thom...,Romanticism,genre painting,NaN,Mythology,NaN,NaN,NaN,NaN,NaN,1.0
2,https://www.wikiart.org/en/john-mclaughlin/num...,1964,NaN,1964,https://uploads0.wikiart.org/images/john-mclau...,Minimalism,abstract,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,https://www.wikiart.org/en/hans-bellmer/the-wo...,1948,NaN,1948,https://uploads5.wikiart.org/images/hans-bellm...,Surrealism,sketch and study,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
4,https://www.wikiart.org/en/eyvind-earle/sierra...,1988,NaN,1988; United States|1988,https://uploads2.wikiart.org/images/eyvind-ear...,Magic Realism,landscape,NaN,cliffs-and-rocks|Natural landscape|Mountain|Sk...,NaN,NaN,NaN,NaN,NaN,4.0

In [8]:
merged_data = artist_artwork.merge(artwork_data, left_on='Link', right_on='url', how='inner')
print(merged_data.shape)
merged_data.head()

(199816, 19)

,Artist_name,Artwork Name,Year,Link,url,Create Date,Create Location,Date,image_url,Style,Genre,Media,tags,Location,Series,Period,Theme,Share,image_n
0,ancient-greek-pottery,Attic Middle Geometric Amphora from Kerameikos,-800,https://www.wikiart.org/en/ancient-greek-potte...,https://www.wikiart.org/en/ancient-greek-potte...,800 BC,NaN,800 BC,https://uploads6.wikiart.org/00238/images/anci...,Geometric,ornament|utensil,terracotta,Vase|Ceramic|Pottery,"National Archaeological Museum, Athens, Greece",NaN,NaN,Amphora,NaN,121750.0
1,ancient-greek-pottery,Attic Late Geometric Amphora. From Athens. By ...,-750,https://www.wikiart.org/en/ancient-greek-potte...,https://www.wikiart.org/en/ancient-greek-potte...,750 BC,NaN,750 BC,https://uploads5.wikiart.org/00238/images/anci...,Geometric,ornament|utensil,terracotta,Vase|Pottery|Urn|Ceramic,"National Archaeological Museum, Athens, Greece",NaN,NaN,Amphora,NaN,121751.0
2,ancient-greek-pottery,Attic Late Geometric Pyxis with Four Horses on...,-735,https://www.wikiart.org/en/ancient-greek-potte...,https://www.wikiart.org/en/ancient-greek-potte...,735 BC,NaN,735 BC,https://uploads3.wikiart.org/00238/images/anci...,Geometric,ornament|utensil,terracotta,NaN,"National Archaeological Museum, Athens, Greece",Relief and plastic,NaN,Pyxis,NaN,121752.0
3,ancient-greek-pottery,Hirschfeld Krater,-735,https://www.wikiart.org/en/ancient-greek-potte...,https://www.wikiart.org/en/ancient-greek-potte...,735 BC,NaN,735 BC,https://uploads4.wikiart.org/00238/images/anci...,Geometric,genre painting|utensil,terracotta,Tonbak|Ceramic,"Metropolitan Museum of Art (Met), New York Cit...",Black-figure,NaN,Krater,NaN,121753.0
4,ancient-greek-pottery,Attic Geometric Trefoil Mouth Oinochoe. From A...,-725,https://www.wikiart.org/en/ancient-greek-potte...,https://www.wikiart.org/en/ancient-greek-potte...,725 BC,NaN,725 BC,https://uploads1.wikiart.org/00238/images/anci...,Geometric,ornament|utensil,terracotta,Pottery|Vase|Ceramic|Serveware|Jug,"National Archaeological Museum, Athens, Greece",NaN,NaN,Oinochoe,NaN,121754.0

## Generate Description

In [9]:
artist_desc_templates = {
    "gender":               "as {value}",
    "birth":                "born{year}{location}",
    "death":                "died{year}{location}",
    "education":            "educated{year}{school}",
    "nationality":          "whose nationality is {value}",
    "ethnicity":            "whose ethnicity is {value}",
    "languages_spoken":     "who spoke {value}",
    "affiliations":         "affiliated to {group}{start_year}{end_year}",
    "religion":             "believing in {religion}{start_year}{end_year}",
    "residences":           "living{location}{start_year}{end_year}",
    "visits":               "touring{location}{start_year}{end_year}",
    "interactions":         "interacting with {name}{year}{location}"
}

In [10]:
for v in demographic_data.values():
    if v["interactions"]:
        print(v["interactions"])
        break

[{'name': 'Schuyler Livingston Parsons', 'role_ego': 'Spouse', 'role_alter': 'Spouse', 'year': 1919, 'location': {'city_full': 'Paris', 'region_full': None, 'country_full': 'France'}}, {'name': 'Adge Baker', 'role_ego': 'Romantic Partner', 'role_alter': 'Romantic Partner', 'year': None, 'location': {'city_full': 'Montparnasse', 'region_full': 'Paris', 'country_full': 'France'}}]

In [11]:
import copy

with open('artist_data/demographic_information.json', 'r') as file:
    demographic_data = json.load(file)
    
data = copy.deepcopy(demographic_data["3d"])

In [12]:
prepmapping = {
    "year": "in",
    "school": "in",
    "start_year": "from",
    "end_year": "to"
}

In [13]:
def clean_up(dict, key, prepmapping=prepmapping):
    if key in dict.keys():
        if dict[key]:
            dict[key] = f" {prepmapping[key]} {dict[key]}"
        else:
            dict[key] = ""

In [16]:
import random
import re
from collections.abc import Iterable

def description_generater(data, artist_desc_templates=artist_desc_templates, seed=42):
    """helper function to generate descriptions for paintings"""
    desc_dict = {}
    random.seed(seed)
    for k, s in artist_desc_templates.items():
        dict_format = {}

        ## Deep copy if dict or list
        if isinstance(data[k], Iterable) and not isinstance(data[k], str):
            dict_format = copy.deepcopy(data[k])
        else:
            dict_format = data[k]

        ## If none for list variables
        if k in ["education", "affiliations", "religion", "residences", "visits", "interactions"] and not dict_format:
            dict_format = {}
            for i in re.findall(r"\{([^{}]+)\}", s):
                dict_format[i] = None
        
        ## Adjust to dict for other format
        if isinstance(dict_format, list) and len(dict_format) > 0 and isinstance(dict_format[0], dict):
            dict_format = random.choice(dict_format)
        elif isinstance(dict_format, list) and len(dict_format) > 0 and not isinstance(dict_format[0], dict):
            dict_format = {"value": "and ".join(dict_format)}
        elif isinstance(dict_format, str):
            dict_format = {"value": dict_format}
        elif not dict_format:
            dict_format = {"value": None}
        
        ## Adjust location and years
        if "location" in dict_format.keys():
            if dict_format["location"]:
                if dict_format["location"]["city_full"]:
                    dict_format["location"] = " at {city_full}".format(**dict_format["location"])
                else:
                    dict_format["location"] = ""
            else:
                dict_format["location"] = ""
        
        for key in ["school", "year", "start_year", "end_year"]:
            clean_up(dict_format, key)
        
        if all(value == "" for value in dict_format.values()):
            dict_format = {key: None for key in dict_format}
        
        desc = s.format(**dict_format)
        
        if "None" not in desc:
            #print(k + ": existing, " + desc)
            desc_dict[k] = desc
        #else:
            #print(k + ": missing, " + desc)
            
    return desc_dict

In [17]:
artist_desc = {}
for artist, data in demographic_data.items():
    artist_desc[artist] = description_generater(data)

In [18]:
artist_desc["joan-mitchell"]

{'gender': 'as female',
 'birth': 'born in 1925 at Chicago',
 'death': 'died in 1992 at Paris',
 'education': 'educated in 1947 in Art Institute of Chicago',
 'nationality': 'whose nationality is American',
 'affiliations': 'affiliated to New York School from 1950',
 'residences': 'living at Vétheuil from 1967 to 1992'}

In [ ]:
with open('artist_data/artist_desc.json', 'w', encoding='utf-8') as f:
    json.dump(artist_desc, f, ensure_ascii=False, indent=2)